spring.application.name=restaurant
spring.datasource.url=jdbc:h2:file:./data/restaurantdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=1234
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=never
spring.jpa.open-in-view=false
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false
batch.informe-restaurantes.salida-path=informes/informe_restaurantes.csv
batch.informe-platos.salida-path=informes/informe_platos.csv
batch.delimiter=;
batch.line-break=\n
batch.informe-menus.salida-path=C:/rutas/de/ejemplo/informe-menus.csv