spring.application.name=loteria
server.port=8080

logging.level.root=WARN
logging.level.com.softtek.loteria=DEBUG
logging.level.AUDIT=INFO

logging.file.name=application.log
logging.file.max-size=10MB
logging.file.max-history=10

logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
